
-- Update Schema for YogIA_Center
-- Run this in the Supabase SQL Editor

-- 1. Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Instructors Table
-- Ensure table exists with correct columns
CREATE TABLE IF NOT EXISTS instructores (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  nombre TEXT NOT NULL,
  biografia TEXT,
  especialidad TEXT,
  foto_url TEXT,
  google_calendar_id TEXT UNIQUE,
  google_refresh_token TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add google_calendar_id column if missing (for existing table)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='instructores' AND column_name='google_calendar_id') THEN
        ALTER TABLE instructores ADD COLUMN google_calendar_id TEXT UNIQUE;
    END IF;
END $$;

-- 3. Class Configuration Table (Services)
-- Ensure table exists
CREATE TABLE IF NOT EXISTS clases_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  duracion INTEGER NOT NULL DEFAULT 60, -- Duration in minutes
  buffer_minutes INTEGER DEFAULT 15, -- Yoga buffer default
  precio DECIMAL(10, 2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add buffer_minutes column if missing
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clases_config' AND column_name='buffer_minutes') THEN
        ALTER TABLE clases_config ADD COLUMN buffer_minutes INTEGER DEFAULT 15;
    END IF;
END $$;

-- 4. Reservations Table
-- Ensure enum type exists
DO $$ BEGIN
  CREATE TYPE estado_reserva AS ENUM ('pendiente', 'confirmada', 'cancelada', 'completada');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Ensure table exists
CREATE TABLE IF NOT EXISTS reservas (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  fecha_inicio TIMESTAMPTZ NOT NULL,
  fecha_fin TIMESTAMPTZ NOT NULL,
  cliente_id UUID REFERENCES auth.users(id), -- Or refer to public.perfiles(id) if used
  instructor_id UUID REFERENCES instructores(id),
  clase_id BIGINT REFERENCES clases_config(id),
  google_event_id TEXT,
  estado estado_reserva DEFAULT 'pendiente',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add check for overlapping bookings (Constraint)
-- Ideally this logic is in application layer or edge function to check Google Calendar too.
-- But a basic exclusion constraint can prevent double booking same instructor in DB.
-- Note: Requires run 'CREATE EXTENSION btree_gist' if needed for exclusion constraint types.
